contributors.txt
This PR is to fulfill my portion of lab 1 and to add my name/email to our contributors file.
=> Add name and email to contributors file

contributors.txt
Updated contributors.txt with my name and email
=> Added Name and Email

contributors.txt, repo_mining/Angel_Quintanilla_CollectFiles.py, repo_mining/Angel_Quintanilla_authorsFileTouches.py, repo_mining/Angel_Quintanilla_scatterplot.py
Here are the scripts I made for the Github Repo mining lab # 1. 
See These files added:
Angel_Quintanilla_authorsFileTouches.py
Angel_Quintanilla_CollectFiles.py
Angel_Quintanilla_executive_summary.pdf
Angel_Quintanilla_scatterplot.py
=> Lab 1 - Scripts for Github Repo Mining

Carbon/navigation/screens/Home/GetData.js, Carbon/navigation/screens/Home/Log.js
=> set up GetData() function

Carbon/components/ChartData.js, Carbon/navigation/screens/Home/ChartData.js, Carbon/navigation/screens/Home/GetData.js, Carbon/navigation/screens/Home/HomeScreen.js, Carbon/navigation/screens/Home/Log.js, Server/api/userEmissions.js, Server/app.js, Server/models/UserEmissions.js
Files Touched/Created++
Carbon/navigation\screens/Home/
++Log.js
This contains all of things related to the log itself, including styling.
A few hooks are used to manage the state of the log and dynamically update the values.
Lots of formatting was included to make it look nice.
TODO:
Nothing needs to be changed in this file currently.
Carbon/navigation\screens/Home/
++GetData.js
Connects to the server through a request based on a specific end point url.
Currently just takes the whole useremissions table and then logs it into the console for debug puprose.
TODO:
Pass in the userID associated with a session token in order to get the relevant data, then calculate the data into a correct format.
The format will be Today = current numbers, yesterday = yesterdays, weekly takes last 7 days and …
=> Added Log feature, as well as implemented some things on the server side. Please read write up for full scale of things created

Carbon/__tests__/components/ChartData.test.js, Carbon/package-lock.json, Carbon/package.json
Added jest, react native testing library, and react test renderer. I also added the folder structure for tests and an example component test.
To use just run `npm run test` to run all tests. To run a specific test do `npm run test <path-to-test>. Tests should be placed in the __tests__ folder. After running a test you get results that indicate if the test passed or failed, as well as information about how many lines were covered by the test. Here is an example test result.  
To make life easier you should use features from the React Native Testing library in conjunction with jest. It provides these useful APIs for rendering components and executing events.
=> Testing dependencies

Carbon/navigation/screens/Browser/BrowserScreen.js, Carbon/navigation/screens/Ranking/RankingScreen.js, Server/api/user.js, Server/api/userEmissions.js, Server/app.js, Server/models/UserEmissions.js, Server/models/UserModel.js, Server/utils/SustainabilityScore.js, Server/utils/UpdateScore.js
Added the Following Parts 
- Backend : 
- Routes for 
- User Table, Routes for : 
- getting a leaderboard page via page #
- getting rank via id
- submitting questionnaire results towards their sustainability_score
- getting user entry via id 
- submitting questionnaire results to add towards their overall score
- User Emissions Table
-  getting all entries from an ID (I can't remember if I did this one lol, I think I did? lol)
-  posting a new emissions entry. 
- Models for 
- User Table 
- User Emissions Table (updated from previous PR implementing this)
- Utilities :  
- Sustainability Score - Maps user to an expected yearly Carbon footprint(ECF) 
- UpdateScore - Changes users global_score based on whether they met their ECF
- Frontend : 
- Ranking Screen  3 tabs  
- Players Local to …
=> Ranking frontend backend pr branch

Carbon/navigation/screens/Browser/BrowserScreen.js, Carbon/navigation/screens/Main/MainContainer.js, Carbon/navigation/screens/Main/ScreenNames.js, Carbon/navigation/screens/index.js, Carbon/package-lock.json, Carbon/package.json
I've created a new component called BrowserScreen.js which allows for easy embedding of websites into the app. This component will be particularly useful in the future when we want to display articles in the education forum section.
I've also added this new component to the navigation tab for easy access. Additionally, I've already used the BrowserScreen.js component to embed our class website for senior design into the education section.
Overall, these changes will greatly improve the user experience by allowing easy access to external content within the app, and laying the foundation for future enhancements to the education section.
Please review and merge at your convenience.
Thank you!
=> Created BrowserScreen.js for website embedding 

Carbon/__tests__/components/EmissionModal.test.js, Carbon/__tests__/components/RecordEmission.test.js, Carbon/navigation/screens/Progress/EmissionModal.js, Carbon/navigation/screens/Progress/RecordEmission.js
I created unit tests for my two components reaching 100% line coverage for both. They mock the various actions that users can do to interact with them. To help implement these tests I had to add a TestID prop to EmissionModal as well as create TestID's for various elements in both components. I also had to comment out a few lines of code that still need to be implemented as they were not able to be tested yet.
=> Added unit tests for RecordEmission and EmissionModal

Carbon/__tests__/screens/ForumScreen.test.js
Adding testing to education forum.
For now it only covers the forum screen, and not the screens that it can navigate to.
As well it will only test that the screen renders, not any specific functionality.
=> Education forum

Carbon/__tests__/navigation/QuizScreen.test.js, Carbon/package-lock.json
This pull request adds unit tests for the QuizScreen component. Specifically, it adds tests to ensure that the component displays a loading message while data is being fetched, renders the quiz name and first question when data is loaded, and shows the final score and completion message when the quiz is completed.
In order to achieve this, I added the following tests:
should show loading message while data is being fetched: This test verifies that the component displays a "Loading" message while the mock data is being fetched from the API.
should render quiz name and first question when data is loaded: This test verifies that the component displays the quiz name and first question when the mock data has been fetched and rendered.
should show final score and completion message when quiz is …
=> Created QuizScreen.test.js

Carbon/__tests__/Progress/GoalSetter.test.js, Carbon/navigation/screens/Progress/GoalSetter.js
Description
This PR adds testing functionality for the GoalSetter component, which is responsible for rendering the goal setting component and making a PUT request to update the user's goals.
Motivation
The GoalSetter component is a critical part of our app's functionality, as it allows users to set and update their goals. In order to ensure that the component functions correctly, we need to add testing functionality to verify that it renders the goal setting component and makes a PUT request to update the user's goals.
Changes
Adds Jest tests for the GoalSetter component to ensure that it renders the goal setting component correctly and makes a PUT request to update the user's goals.
Added Jest test for the GoalSetter component.
Verified that the tests pass locally.
=> add testing for goal setter

Carbon/__tests__/components/ChartData.test.js, Carbon/__tests__/navigation/screens/Home/GetData.test.js, Carbon/__tests__/navigation/screens/Home/Log.test.js, Carbon/components/ChartData.js, Carbon/navigation/screens/Home/Log.js
Added testing that will cover most of my parts, some of it is not working yet, needs to be fixed.
=> Log sprint2 final

Carbon/components/EmailInput.js, Carbon/components/ForgotPasswordNavButton.js, Carbon/components/LoginButton.js, Carbon/components/LoginNavButton.js, Carbon/components/PasswordInput.js, Carbon/components/SignUpButton.js, Carbon/components/SignUpNavButton.js, Carbon/navigation/screens/Login-SignUp/LoginScreen.js, Carbon/navigation/screens/Login-SignUp/SignUpScreen.js
I created the Login screen along with the components that make up the screen.
Login Screen
- Carbon Logo
- Email Input
- Password Input
- Forgot Password link
- Login Button
- Sign Up screen link
- Sign Up Screen
Currently, the buttons and links have no functionality but that will be added in the next sprint.
=> Login Screen

Carbon/components/LoginNavButton.js, Carbon/components/SignUpButton.js, Carbon/navigation/screens/Login-SignUp/SignUpScreen.js
I created the Sign Up screen along with the components that make up the screen.
Sign Up Screen
- Carbon Logo
- Email Input
- Two Password Inputs
- Sign Up Button
- Login screen link
Currently, the buttons and links have no functionality but that will be added in the next sprint.
=> Sign Up Screen

Server/app.js
We forgot the / in ./api/goal so the server crashed on startup :skull:
=> Critical Typo Fix

Carbon/__tests__/components/EmailInput.test.js, Carbon/__tests__/components/ForgotPasswordNavButton.test.js, Carbon/__tests__/components/LoginButton.test.js, Carbon/__tests__/components/LoginNavButton.test.js, Carbon/__tests__/components/LoginScreen.test.js, Carbon/__tests__/components/PasswordInput.test.js, Carbon/__tests__/components/SignUpButton.test.js, Carbon/__tests__/components/SignUpNavButton.test.js, Carbon/__tests__/components/SignUpScreen.test.js
I wrote unit tests for each component created for the Login and Sign Up screens. I also wrote unit tests for both the Login and Sign Up screens to ensure all of it's components render properly. The tests pass with 100% line coverage except for SignUpScreen.test.js, which will be fixed next time.
=> Unit Tests for Login/SignUp screens and components

Carbon/navigation/screens/Progress/GoalSetter.js, Carbon/package-lock.json, Carbon/package.json, Server/api/goal.js
This PR effectively refactors the functionality of goal setting
- Set the goal by logged in userID using Erik's new authentication process
- Update the slider component to use a component that is no longer deprecated and works on iPhone and Android (+ Web)
Still left to do after this PR:
-  Add query plus component that displays how much their goal will cut in CO2 per month in pounds. 
- Add more robust unit tests
- Add goal setting functionality to progress screen plus button
=> Goal setting refactor 1

Carbon/components/PopUpMenu.js, Carbon/config/Api.js, Carbon/navigation/screens/Main/MainContainer.js, Carbon/navigation/screens/Progress/ProgressScreen.js, Server/api/userEmissions.js
- **PopUpMenu.js**
- Contains the pop-up menu component and its styling.
- **MainContainer.js**
- Added the `PopUpMenu` component.
- Adjusted the header height to a fixed number for both iOS and Android.
- **ProgressScreen.js**
- Removed the `Record Emissions` and `Add Goal` buttons.
- **Api.js**
- Switched the `API_URL` from localhost to the server URL.
- **UserModel.js**
- Renamed the the path of `user_table` to its correct model.
- **PopUpMenu.js**
- **MainContainer.js**
- **Unit Testing**
=> Created a pop-up menu for Progress Screen

Carbon/navigation/screens/Quiz/QuizScreen.js, Server/api/user.js
This pull request introduces changes to the quiz screen in order to improve the user experience and provide a scoring system. The changes include the following:
- Clicking an answer will now highlight it in grey, and the user will need to confirm their selection.
- If the user selects the correct answer, the answer will highlight in green, and the score will increase accordingly.
- If the user selects the incorrect answer, the answer will highlight in red, and the score will not increase.
- If the user gets a 100% score, the score will be posted to the database to update their score.
- If the user does not get a 100% score, they will be prompted to redo the quiz.
These changes will enhance the user experience and encourage users to take quizzes seriously by introducing a scoring system. …
=> Update Quiz Screen with Answer Confirmation and Scoring System

Carbon/components/PopUpMenu.js, Carbon/navigation/screens/Main/MainContainer.js, Carbon/navigation/screens/Quiz/QuizScreen.js, Carbon/styling/Colors.js
- **`QuizScreen.js`**
- Overall UI improvements.
- Removed tab bar from quiz screen so users will not be able to navigate anywhere else. It helps users focus on the quiz.
- **Others**
- Various code cleanup on other files.
- **`QuizScreen.js`**
- Added an exit modal for the quiz that lets user leave the quiz.
=> Quiz Screen UI improvements

Carbon/navigation/screens/Progress/RecordFood.js, Carbon/navigation/screens/Progress/RecordRecycling.js, Carbon/navigation/screens/Progress/RecordTransportation.js
This PR updates the View tags in the emission screens into ScrollView. This is a necessary fix to address different sized devices not being able to access all of the content on the screen.
=> Add ScrollView to each emission screen

Carbon/navigation/screens/Main/ScreenNames.js, Carbon/navigation/screens/Progress/GoalSetter.js, Carbon/util/Goals.js, Server/api/userEmissions.js
This PR allows users to visualize how many pounds of CO2 they'd cut this month based on the goal they are setting.
=> Goal Setting Refactor - Calculate Pounds of CO2 Cut by Goal %

Carbon/calculations/PredictInput.js, Carbon/navigation/screens/Progress/Log.js, Carbon/navigation/screens/Progress/ProgressScreen.js, Carbon/package-lock.json, Carbon/package.json, package-lock.json
Implementing machine learning to make a simple prediction. Right now it needs to be hooked up to the front end properly.
Moved the log.
Made the log look nice as well and hooked it up to add data when there is no data available.
=> Started prediction and added fixes

Carbon/calculations/PredictInput.js, Carbon/components/ChartData.js, Carbon/navigation/screens/Progress/Log.js, Carbon/navigation/screens/Progress/ProgressScreen.js
Fixed all of the UI issues that were pointed out. 
Removed "lifestyle" from charts
Fixed misc bugs
Added 
TODO-Add unit tests
=> Bug fixing and testing

Carbon/components/CalculationsButton.js, Carbon/navigation/screens/Main/MainContainer.js, Carbon/navigation/screens/Main/ScreenNames.js, Carbon/navigation/screens/Settings/CalculationScreen.js, Carbon/navigation/screens/Settings/SettingsScreen.js
This PR implements the following
- Create CalculationsButton component which links to CalculationScreen 
- Add CalculationButton to SettingScreen
- Create CalculationScreen which informs users how are calculations are calculated
- Update ScreenNames and MainContainer with CalculationScreen
=> Add calculations to setting screen

Carbon/navigation/screens/Main/MainContainer.js, Carbon/navigation/screens/Main/ScreenNames.js, Carbon/navigation/screens/Progress/RecordElectricity.js, Carbon/navigation/screens/Progress/RecordEmission.js
- Created RecordElectricity screen and added it as an option in RecordEmission. It saves co2 emitted from a users home electricity to the home_emission column.
=> Electricity Screen

Carbon/__tests__/navigation/screens/Forum/ForumScreen.test.js, Carbon/components/ForumCards.js, Carbon/navigation/screens/Forum/ForumScreen.js
Simple testing for Forum screen.
=> getting 88% coverage for forum

Carbon/util/UserManagement.js
=> fixed signup button profanity
